### ISSUE TITLE
RSS-then-average & Average-then-rss

### ISSUE THREAD

**Issue by hellopipu** [cai2r/fastMRI_prostate#2]
Hi,

Thanks for the great work.

For T2 reconstruction, I found the code using the rss-then-avg pipeline, so 3 k-space data correspond to the final reconstruction. This is a little different from the fastMRI knee and brain dataset and will make a difference in training new machine learning tools.

To make it consistent for the other dataset and convenient for training, I tried to use avg-then-rss, which can result in a one-to-one correspondence between k-space and reconstruction. However, I found in this way, the image looks smoother. 

![image](https://github.com/cai2r/fastMRI_prostate/assets/122708097/a8984401-a1c9-437c-8351-2cceb5f7f33c)

What's your opinion on the difference between the two pipelines? Do you have any suggestions? Thank you.

**Comment by radhikatibrewala** [comment]
Hello,

Thanks for your question. Here is the summary of the different methods you mentioned:

**Method 1**
Average then RSS: this pipeline results in some phase cancellation but has no g-factor noise amplification. However, it is more sensitive to motion artifacts, which is why we chose Method 2 for our reconstruction pipeline code.

**Method 2**
RSS then average : this pipeline results in images that are less sensitive to motion artifacts but has noise amplification due to an increased g-factor, however differs from the knee and brain data reconstruction.

Overall, the difference between the two methods is not very large, and providing all the averages gives you the flexibility to the preferred method to be more compatible with the other datasets/fastMRI code repository.

Thank you,
Radhika
